language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - node_modules

script:
  - yarn global add typings
  - typings install
  - tsc --version
  - yarn transpile
  - ls -l
  - ls -l lib
  - cat lib/index.js
  - cat .npmignore

deploy:
  provider: npm
  email: olegman.ru@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-redux
